### ISSUE TITLE
Feature request: possibility to specify a date instead of days

### ISSUE THREAD

**Issue by eni23** [adfinis-sygroup/rmd.io#6]
One feature i am missing is the possibility to specify an specific date instead of days. For example if i send  mail to 22-08-2017@rmd.io i would get a reminder mail at this date.

**Comment by winged** [comment]
Should be fairly simple, by extending `mails.tools.get_delay_addresses_from_recipient()` (to detect the date-formatted addresses) and then adjusting the `import_mail` method in `mails.management.commands.import.Command` (roughly around line 80).

**Comment by trowik** [comment]
#94
